package com.example.demo;

import com.example.demo.model.Vocab;
import com.example.demo.repository.VocabRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

@Component
public class DataLoader implements CommandLineRunner {

    private final VocabRepository vocabRepository;

    // Inject the repository via constructor
    public DataLoader(VocabRepository vocabRepository) {
        this.vocabRepository = vocabRepository;
    }

    @Override
    public void run(String... args) throws Exception {
        
        if (vocabRepository.count() == 0) {
            vocabRepository.save(new Vocab("Adept", "Highly skilled or proficient"));
            vocabRepository.save(new Vocab("Belligerent", "Hostile and aggressive"));
            vocabRepository.save(new Vocab("Cacophony", "A harsh, discordant mixture of sounds"));
            vocabRepository.save(new Vocab("Debilitate", "To weaken or make feeble"));
            vocabRepository.save(new Vocab("Ebullient", "Overflowing with enthusiasm"));
            vocabRepository.save(new Vocab("Facilitate", "To make easier or help bring about"));
            vocabRepository.save(new Vocab("Garrulous", "Excessively talkative"));
            vocabRepository.save(new Vocab("Harangue", "A lengthy and aggressive speech"));
            vocabRepository.save(new Vocab("Iconoclast", "One who attacks traditional beliefs"));
            vocabRepository.save(new Vocab("Juxtapose", "To place side by side for comparison"));
            vocabRepository.save(new Vocab("Keen", "Having a sharp edge or intellect"));
            vocabRepository.save(new Vocab("Lament", "To mourn or express sorrow"));
            vocabRepository.save(new Vocab("Malleable", "Capable of being shaped or changed"));
            vocabRepository.save(new Vocab("Nefarious", "Wicked or criminal"));
            vocabRepository.save(new Vocab("Obfuscate", "To confuse or make unclear"));
            vocabRepository.save(new Vocab("Palpable", "Able to be touched or felt"));
            vocabRepository.save(new Vocab("Quell", "To suppress or put an end to"));
            vocabRepository.save(new Vocab("Rancor", "Bitter resentment or ill will"));
            vocabRepository.save(new Vocab("Sagacious", "Wise or shrewd"));
            vocabRepository.save(new Vocab("Tangible", "Capable of being touched; real"));
            vocabRepository.save(new Vocab("Ubiquitous", "Present everywhere"));
            vocabRepository.save(new Vocab("Vacillate", "To waver between different opinions"));
            vocabRepository.save(new Vocab("Wane", "To decrease gradually"));
            vocabRepository.save(new Vocab("Xenophobia", "Fear or hatred of foreigners"));
            vocabRepository.save(new Vocab("Yearn", "To have a strong desire"));
            vocabRepository.save(new Vocab("Zealous", "Filled with passion or enthusiasm"));
            vocabRepository.save(new Vocab("Ameliorate", "To improve or make better"));
            vocabRepository.save(new Vocab("Burgeon", "To grow or flourish rapidly"));
            vocabRepository.save(new Vocab("Capitulate", "To surrender or give in"));
            vocabRepository.save(new Vocab("Deleterious", "Causing harm or damage"));
            vocabRepository.save(new Vocab("Enervate", "To weaken or drain energy"));
            vocabRepository.save(new Vocab("Flummox", "To confuse or perplex"));
            vocabRepository.save(new Vocab("Gregarious", "Sociable; fond of company"));
            vocabRepository.save(new Vocab("Hapless", "Unlucky; unfortunate"));
            vocabRepository.save(new Vocab("Impetuous", "Acting quickly without thought"));
            vocabRepository.save(new Vocab("Judicious", "Having good judgment"));
            vocabRepository.save(new Vocab("Kudos", "Praise or acclaim"));
            vocabRepository.save(new Vocab("Lethargic", "Sluggish or lacking energy"));
            vocabRepository.save(new Vocab("Mundane", "Commonplace or ordinary"));
            vocabRepository.save(new Vocab("Nonchalant", "Calm and unconcerned"));
            vocabRepository.save(new Vocab("Ostentatious", "Showy or pretentious"));
            vocabRepository.save(new Vocab("Perfunctory", "Done without care or interest"));
            vocabRepository.save(new Vocab("Querulous", "Complaining or whining"));
            vocabRepository.save(new Vocab("Recalcitrant", "Stubbornly disobedient"));
            vocabRepository.save(new Vocab("Serendipity", "Luck in finding good things by chance"));
            vocabRepository.save(new Vocab("Taciturn", "Reserved or uncommunicative"));
            vocabRepository.save(new Vocab("Abhor", "To hate deeply"));
            vocabRepository.save(new Vocab("Beguile", "To charm or deceive"));
            vocabRepository.save(new Vocab("Cajole", "To persuade by flattery"));
            vocabRepository.save(new Vocab("Dauntless", "Fearless; undaunted"));
            vocabRepository.save(new Vocab("Egregious", "Outstandingly bad"));
            vocabRepository.save(new Vocab("Fervent", "Passionate or intense"));
            vocabRepository.save(new Vocab("Guile", "Sly or cunning intelligence"));
            vocabRepository.save(new Vocab("Hinder", "To create difficulties or delay"));
            vocabRepository.save(new Vocab("Immaculate", "Perfectly clean or spotless"));
            vocabRepository.save(new Vocab("Jocular", "Joking or humorous"));
            vocabRepository.save(new Vocab("Knavery", "Dishonest or unscrupulous behavior"));
            vocabRepository.save(new Vocab("Luminous", "Emitting light; bright"));
            vocabRepository.save(new Vocab("Magnanimous", "Generous or forgiving"));
            vocabRepository.save(new Vocab("Nurture", "To care for and encourage growth"));
            vocabRepository.save(new Vocab("Ominous", "Threatening or foreboding"));
            vocabRepository.save(new Vocab("Paragon", "A model of excellence"));
            vocabRepository.save(new Vocab("Querulous", "Complaining in a whining manner"));
            vocabRepository.save(new Vocab("Resolute", "Determined; unwavering"));
            vocabRepository.save(new Vocab("Stoic", "Enduring pain or hardship without complaint"));
            vocabRepository.save(new Vocab("Trepidation", "Fear or anxiety about the future"));
            vocabRepository.save(new Vocab("Uncanny", "Strange or mysterious"));
            vocabRepository.save(new Vocab("Verbose", "Using more words than needed"));
            vocabRepository.save(new Vocab("Wistful", "Full of longing or desire"));
            vocabRepository.save(new Vocab("Yield", "To give way or submit"));
            vocabRepository.save(new Vocab("Zephyr", "A gentle breeze"));
            vocabRepository.save(new Vocab("Altruistic", "Unselfishly concerned for others"));
            vocabRepository.save(new Vocab("Benevolent", "Kind and generous"));
            vocabRepository.save(new Vocab("Censure", "To express strong disapproval"));
            vocabRepository.save(new Vocab("Defer", "To postpone or delay"));
            vocabRepository.save(new Vocab("Ebullient", "Cheerful and full of energy"));
            vocabRepository.save(new Vocab("Furtive", "Secretive; stealthy"));
            vocabRepository.save(new Vocab("Grandiose", "Impressive or magnificent"));
            vocabRepository.save(new Vocab("Harbinger", "A person or thing that signals the approach of another"));
            vocabRepository.save(new Vocab("Impetuous", "Acting without thinking"));
            vocabRepository.save(new Vocab("Jaded", "Tired or lacking enthusiasm"));
            vocabRepository.save(new Vocab("Kindred", "Similar in nature or character"));
            vocabRepository.save(new Vocab("Lethargy", "Lack of energy; sluggishness"));
            vocabRepository.save(new Vocab("Mollify", "To soothe or calm"));
            vocabRepository.save(new Vocab("Nefarious", "Wicked or criminal"));
            vocabRepository.save(new Vocab("Obsolete", "No longer in use"));
            vocabRepository.save(new Vocab("Pensive", "Deep in thought"));
            vocabRepository.save(new Vocab("Quixotic", "Unrealistic and impractical"));
            vocabRepository.save(new Vocab("Rhetoric", "The art of persuasive speaking or writing"));
            vocabRepository.save(new Vocab("Sanguine", "Optimistic or positive"));
            vocabRepository.save(new Vocab("Tangible", "Capable of being touched"));
            vocabRepository.save(new Vocab("Ubiquitous", "Present everywhere"));
            vocabRepository.save(new Vocab("Vacillate", "To waver between decisions"));
            vocabRepository.save(new Vocab("Wrath", "Extreme anger"));
            vocabRepository.save(new Vocab("Xenial", "Hospitable, especially to strangers"));
            vocabRepository.save(new Vocab("Aberration", "A departure from what is normal or expected"));
            vocabRepository.save(new Vocab("Blithe", "Showing casual or cheerful indifference"));
            vocabRepository.save(new Vocab("Circumspect", "Wary and unwilling to take risks"));
            vocabRepository.save(new Vocab("Dichotomy", "A division between two contrasting things"));
            vocabRepository.save(new Vocab("Ethereal", "Extremely delicate and light"));
            vocabRepository.save(new Vocab("Felicity", "Intense happiness or joy"));
            vocabRepository.save(new Vocab("Galvanize", "To shock or excite into action"));
            vocabRepository.save(new Vocab("Hubris", "Excessive pride or self-confidence"));
            vocabRepository.save(new Vocab("Insidious", "Proceeding subtly but with harmful effects"));
            vocabRepository.save(new Vocab("Juxtaposition", "Placement of two things side by side for contrast"));
            vocabRepository.save(new Vocab("Kinetic", "Relating to or resulting from motion"));
            vocabRepository.save(new Vocab("Laconic", "Using very few words"));
            vocabRepository.save(new Vocab("Meticulous", "Showing great attention to detail"));
            vocabRepository.save(new Vocab("Nebulous", "Unclear or vague"));
            vocabRepository.save(new Vocab("Ostensible", "Stated or appearing to be true, but not necessarily so"));
            vocabRepository.save(new Vocab("Parsimony", "Extreme unwillingness to spend money or resources"));
            vocabRepository.save(new Vocab("Quagmire", "A difficult or precarious situation"));
            vocabRepository.save(new Vocab("Reverence", "Deep respect for someone or something"));
            vocabRepository.save(new Vocab("Scrupulous", "Extremely attentive to details or morals"));
            vocabRepository.save(new Vocab("Tenacious", "Holding firmly to something; persistent"));
            vocabRepository.save(new Vocab("Usurp", "To take a position of power illegally or by force"));
            vocabRepository.save(new Vocab("Vicarious", "Experienced through the feelings of another"));
            vocabRepository.save(new Vocab("Wary", "Cautious and watchful"));
            vocabRepository.save(new Vocab("Xenolith", "A rock fragment enclosed in another rock"));
            vocabRepository.save(new Vocab("Yielding", "Giving way under pressure"));
            vocabRepository.save(new Vocab("Zenith", "The highest point or peak"));
            vocabRepository.save(new Vocab("Acrimonious", "Angry and bitter in tone or language"));
            vocabRepository.save(new Vocab("Banal", "Lacking originality; boring"));
            vocabRepository.save(new Vocab("Candor", "The quality of being open and honest"));
            vocabRepository.save(new Vocab("Deft", "Skillful and quick in movement"));
            vocabRepository.save(new Vocab("Eloquent", "Fluent and persuasive in speaking or writing"));
            vocabRepository.save(new Vocab("Frivolous", "Not having any serious purpose"));
            vocabRepository.save(new Vocab("Gamut", "The complete range or scope of something"));
            vocabRepository.save(new Vocab("Heinous", "Utterly wicked or evil"));
            vocabRepository.save(new Vocab("Illicit", "Forbidden by law or custom"));
            vocabRepository.save(new Vocab("Judicious", "Having or showing good judgment"));
            vocabRepository.save(new Vocab("Kaleidoscopic", "Continually changing and colorful"));
            vocabRepository.save(new Vocab("Lucid", "Expressed clearly; easy to understand"));
            vocabRepository.save(new Vocab("Myriad", "A countless or extremely great number"));
            vocabRepository.save(new Vocab("Nostalgia", "A sentimental longing for the past"));
            vocabRepository.save(new Vocab("Obstinate", "Stubbornly refusing to change one’s opinion"));
            vocabRepository.save(new Vocab("Pragmatic", "Dealing with things sensibly and realistically"));
            vocabRepository.save(new Vocab("Quaint", "Attractively old-fashioned"));
            vocabRepository.save(new Vocab("Resilient", "Able to recover quickly from difficulties"));
            vocabRepository.save(new Vocab("Substantiate", "To provide evidence to support a claim"));
            vocabRepository.save(new Vocab("Transitory", "Not permanent; lasting for a short time"));
            vocabRepository.save(new Vocab("Unilateral", "Performed by one side only"));
            vocabRepository.save(new Vocab("Voracious", "Having a very eager approach to an activity"));
            vocabRepository.save(new Vocab("Wary", "Careful and cautious"));
            vocabRepository.save(new Vocab("Yearling", "An animal that is one year old"));
            vocabRepository.save(new Vocab("Zealot", "A person who is fanatical in pursuit of their ideals"));
            vocabRepository.save(new Vocab("Ambivalent", "Having mixed feelings about something"));
            vocabRepository.save(new Vocab("Bombastic", "High-sounding but with little meaning"));
            vocabRepository.save(new Vocab("Concur", "To agree with someone or something"));
            vocabRepository.save(new Vocab("Disparate", "Essentially different in kind"));
            vocabRepository.save(new Vocab("Ebullience", "The quality of being cheerful and full of energy"));
            vocabRepository.save(new Vocab("Facetious", "Treating serious issues with inappropriate humor"));
            vocabRepository.save(new Vocab("Gravitas", "Dignity, seriousness, or solemnity of manner"));
            vocabRepository.save(new Vocab("Hiatus", "A pause or gap in a sequence or process"));
            vocabRepository.save(new Vocab("Imminent", "About to happen"));
            vocabRepository.save(new Vocab("Kudos", "Praise and honor received for an achievement"));
            vocabRepository.save(new Vocab("Lamentable", "Deplorably bad or unsatisfactory"));
            vocabRepository.save(new Vocab("Mendacious", "Not telling the truth; lying"));
            vocabRepository.save(new Vocab("Nonplussed", "Surprised and confused so as not to know how to react"));
            vocabRepository.save(new Vocab("Opaque", "Not transparent; difficult to understand"));
            vocabRepository.save(new Vocab("Perennial", "Lasting for a long time or continually recurring"));
            vocabRepository.save(new Vocab("Quell", "To put an end to something"));
            vocabRepository.save(new Vocab("Reclusive", "Avoiding the company of others; solitary"));
            vocabRepository.save(new Vocab("Stagnant", "Not moving or flowing; inactive"));
            vocabRepository.save(new Vocab("Trivial", "Of little value or importance"));
            vocabRepository.save(new Vocab("Undulate", "To move with a smooth wave-like motion"));
            vocabRepository.save(new Vocab("Vigilant", "Keeping careful watch for danger"));
            vocabRepository.save(new Vocab("Whimsical", "Playfully quaint or fanciful"));
            vocabRepository.save(new Vocab("Xylograph", "An engraving on wood"));
            vocabRepository.save(new Vocab("Yearning", "A feeling of intense longing"));
            vocabRepository.save(new Vocab("Zany", "Amusingly unconventional and eccentric"));
            vocabRepository.save(new Vocab("Affable", "Friendly, easy to talk to"));
            vocabRepository.save(new Vocab("Brazen", "Bold and without shame"));
            vocabRepository.save(new Vocab("Complacent", "Smug or self-satisfied"));
            vocabRepository.save(new Vocab("Diligent", "Showing care in one’s work"));
            vocabRepository.save(new Vocab("Empathy", "The ability to understand another’s feelings"));
            vocabRepository.save(new Vocab("Futile", "Incapable of producing any useful result"));
            vocabRepository.save(new Vocab("Guileless", "Devoid of deceit; innocent"));
            vocabRepository.save(new Vocab("Homage", "Special honor or respect shown"));
            vocabRepository.save(new Vocab("Incredulous", "Unwilling to believe something"));
            vocabRepository.save(new Vocab("Jubilant", "Feeling great happiness and triumph"));
            vocabRepository.save(new Vocab("Kinship", "A sense of connection or relationship"));
            vocabRepository.save(new Vocab("Levity", "Lack of seriousness; humor"));
            vocabRepository.save(new Vocab("Melancholy", "A feeling of deep sadness"));
            vocabRepository.save(new Vocab("Notorious", "Famous for something bad"));
            vocabRepository.save(new Vocab("Omnipotent", "Having unlimited power"));
            vocabRepository.save(new Vocab("Perceptive", "Having or showing keen insight"));
            vocabRepository.save(new Vocab("Quizzical", "Showing mild amusement or curiosity"));
            vocabRepository.save(new Vocab("Rebuke", "To criticize sharply"));
            vocabRepository.save(new Vocab("Stoic", "Showing no emotion despite hardship"));
            vocabRepository.save(new Vocab("Trepid", "Fearful or timid"));
            vocabRepository.save(new Vocab("Utilitarian", "Designed for practical use"));
            vocabRepository.save(new Vocab("Venerable", "Accorded great respect due to age or wisdom"));
            vocabRepository.save(new Vocab("Wistful", "Having a feeling of vague longing"));
            vocabRepository.save(new Vocab("Xeric", "Characterized by dry conditions"));
            vocabRepository.save(new Vocab("Yielding", "Complying with the requests of others"));
            vocabRepository.save(new Vocab("Zephyr", "A soft, gentle breeze"));


        }
    }
}
